#!/bin/bash
#SBATCH -N 1
#SBATCH -C cpu
#SBATCH -q debug
#SBATCH -J cs267
#SBATCH -t 00:30:00

#run the application:
srun -n 1 ./serial -n 100 -s 1
srun -n 1 ./serial -n 200 -s 1
srun -n 1 ./serial -n 500 -s 1
srun -n 1 ./serial -n 1000 -s 1
srun -n 1 ./serial -n 2000 -s 1
srun -n 1 ./serial -n 5000 -s 1
srun -n 1 ./serial -n 10000 -s 1
srun -n 1 ./serial -n 20000 -s 1
srun -n 1 ./serial -n 50000 -s 1
srun -n 1 ./serial -n 100000 -s 1
